### ISSUE TITLE
RFC3339 with millis, micros and nanos support

### ISSUE THREAD

**Issue by STPR** [Blobfolio/utc2k#1]
Hello,

Chrono and humantime both support the RFC3339 format ouput with milliseconds, microseconds and nanoseconds:
chrono/humantime (RFC3339  with microseconds): 2021-12-13T16:18:14.662840Z
utc2k: 2021-12-13 16:20:09

Do you think it could be possible to add those features to utc2k without impacting the speed ?

**Comment by joshstoik1** [comment]
`Utc2k` time is only accurate to the second, but I could add an allocating `to_rfc3339` method that would produce a `String` formatted like `1990-12-31T23:59:60Z` if you would find that useful.

Performance-wise, it could be done similarly to `Utc2k::to_string`; the buffer would just need to be one byte bigger for the trailing "Z".

**Comment by joshstoik1** [comment]
All set!

Precision is still limited to seconds — the whole library operates on that scale — but I added `to_rfc3339` methods to both `Utc2k` and `FmtUtc2k` in version `0.3.2`.

```rust
use utc2k::{FmtUtc2k, Utc2k};

let fmt = FmtUtc2k::from(Utc2k::MIN_UNIXTIME);
assert_eq!(fmt.to_rfc3339(), "2000-01-01T00:00:00Z");

let date = Utc2k::new(2021, 12, 13, 11, 56, 1);
assert_eq!(date.to_rfc3339(), "2021-12-13T11:56:01Z");
```

Interestingly, the performance is actually _better_ than `to_string` because it doesn't run through the `std::fmt::Display` trait:

```
utc2k::FmtUtc2k::to_string()                24.08 ns
utc2k::FmtUtc2k::to_rfc3339()               15.57 ns
```

**Comment by STPR** [comment]
Thank you 😀

Since Utc2k::now() doesn't return the local time but UTC+0, I think it's better to have an rfc3339 format output to avoid errors.

**Comment by joshstoik1** [comment]
Thanks for raising the issue, @STPR! I fully agree. I've been manually reformatting output to RFC3339 for a few projects anyway. It makes much more sense to handle it directly within the library. :wink:
