### ISSUE TITLE
1900s

### ISSUE THREAD

**Issue by v1gnesh** [Blobfolio/utc2k#3]
Hey,

Great work with this project, and thank you for sharing as open source.

Is there any chance you could extend this to include the 1900s?
I see it's not as easy as updating the `LEAP_YEARS` const declaration 😅

A slower path for 1900s is fine, if perf was a reason for sticking to 2000+

Thanks for considering, I was really relieved to find that this exists.
Real-world data having dates from 1996 and such is making me sad. 
I'm working with ordinal dates and this crate complements some necessary manual implementations (day of year to rfc3339) very well.

**Comment by joshstoik1** [comment]
Thanks @v1gnesh!

I feel you about 1996 — I have logs going back that far too! — but this library takes advantage of a number of memory optimizations and mathematical shortcuts that, purely by chance, _only_ apply to the current century (`2000..=2099`). The previous and next centuries are fundamentally incompatible.

For projects requiring more nuanced datetime handling, you'll need a library like [chrono](https://crates.io/crates/chrono) or [time](https://crates.io/crates/time). There's no way around it.

But a case could be made for mixing and matching when performance is critical and most dates are expected to be within `utc2k`'s range; you'd just need to parse conditionally, like:

```rust
// When starting with a timestamp:
if let Some(happy) = u32::try_from(raw).ok().and_then(|t| Utc2k::checked_from_unixtime(t).ok()) {
    // You've got a valid Utc2k instance to work with!
}
else {
    // A fallback is required.
}

// When starting with a date(time) string:
if let Some(happy) = raw.starts_with("20").then(|| Utc2k::try_from(raw).ok()) {
    // You've got a valid Utc2k instance to work with!
}
else {
    // A fallback is required.
}
```

If you see any opportunities for `utc2k` to make mixing and matching easier, please let me know!

**Comment by v1gnesh** [comment]
@joshstoik1 the thing with this is, the return type of a function that does this will have to switch between Utc2k or something else.
Can return a String (`to_rfc3339` string for Utc2k) in either case, but in case where Utc2k is being serializing to some other type in a separate impl, do you have any suggestion on how to do a conditional impl... would macros help for this?

**Comment by joshstoik1** [comment]
Hey @v1gnesh,

It gets more complicated if you need to keep the intermediate structures (versus just a `String` or `u16` or whatever). In such cases, I would suggest making an `enum` to hold both types and pass through any common methods you need, including de/serialization helpers.

Off the top of my head — please excuse any typos, haha — something like this:

```rust
use utc2k::Utc2k;
use time::OffsetDateTime; // For example.

#[derive(debug, clone, copy)]
pub enum AnyDate {
    Happy(Utc2k),
    Sad(OffsetDateTime),
}

impl AnyDate {
    /// # New From Timestamp.
    pub fn from_timestamp(raw: i64) -> Option<Self> {
        u32::try_from(raw)
            .ok()
            .and_then(|t| Utc2k::checked_from_unixtime(t).ok().map(Self::Happy))
            .or_else(|| OffsetDateTime::from_unix_timestamp(raw).ok().map(Self::Sad))
    }
}

impl AnyDate {
    /// # Ordinal.
    pub fn ordinal(self) -> u16 {
        match self {
            Self::Happy(d) => d.ordinal(),
            Self::Sad(d) => d.ordinal(),
        }
    }

    /// # Unix Timestamp.
    pub fn unix_timestamp(self) -> i64 {
        match self {
            Self::Happy(d) -> i64::from(d.unixtime()),
            Self::Sad(d) -> d.unix_timestamp(),
        }
    }
}
```

If you're using `serde` for de/serialization, something like this will do the trick:

```rust
use serde::{
    de,
    Deserialize,
    ser,
    Serialize,
};

impl<'de> Deserialize<'de> for AnyDate {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where D: de::Deserializer<'de> {
        let raw: i64 = Deserialize::deserialize(deserializer)?;
        Self::from_timestamp(raw)
            .map_err(|_| de::Error::custom("invalid timestamp"))
    }
}

impl Serialize for AnyDate {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where S: ser::Serializer {
        serializer.serialize_i64(self.unix_timestamp())
    }
}
```

The above example assumes you'd be storing the values as timestamps, but any format understood by both would work just fine.

It is also worth noting that you by doing this yourself, you won't need the internal `serde` support for either `utc2k` or `time`.

Do these examples make sense? I'd be happy to go into more detail if there's anything you're unsure about.

**Comment by v1gnesh** [comment]
Thanks for taking the time to show these, they're very helpful!
Once again thanks for making awesome stuff & sharing 👌

**Comment by joshstoik1** [comment]
No trouble at all. Let me know if you run into any walls!
